# Generated by Django 5.2.1 on 2025-06-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ('title',)},
        ),
        migrations.RenameField(
            model_name='note',
            old_name='text',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='note',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
