# Generated by Django 5.2.1 on 2025-06-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_note_options_rename_text_note_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
