# Generated by Django 5.2.1 on 2025-06-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_applicantprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantprofile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
