# Generated by Django 5.2.1 on 2025-06-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_applicantprofile_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantprofile',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
