# Generated by Django 5.2.1 on 2025-06-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_category_alter_note_options_note_favourites_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='in_basket',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='note',
            name='favourites',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
