# Generated by Django 5.2.1 on 2025-06-10 11:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_note_in_basket_alter_note_favourites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='note',
            name='in_basket',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
