# Generated by Django 5.2.1 on 2025-06-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_applicantprofile_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantprofile',
            name='description',
        ),
        migrations.RemoveField(
            model_name='applicantprofile',
            name='dob',
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
