# Generated by Django 5.2.1 on 2025-06-10 11:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_note_content_alter_note_in_basket'),
    ]

    operations = [
        migrations.CreateModel(
            name='especial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', ckeditor.fields.RichTextField()),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
