# Generated by Django 5.2.1 on 2025-06-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_applicantprofile_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantprofile',
            name='code_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
