# Generated by Django 5.2.1 on 2025-06-10 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_especial_alter_note_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='especial',
        ),
    ]
