# Generated by Django 5.2.1 on 2025-06-12 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_applicantprofile_code_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantprofile',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
