# Generated by Django 5.2.1 on 2025-06-13 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, default='Noname', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('slug', 'owner')},
        ),
    ]
